### ISSUE TITLE
Make Screenshot and Screen Recorder utility

### ISSUE THREAD

**Issue by kiraio-moe** [kiraio-moe/ArisStudio#2]
Create a screenshot utility to be used in story mode or character state preview mode and screen recorder utility in story mode.
The utility have options to choose output format and resolution.

~~The initial plan was to use Unity built-in Screen Recorder package.~~
Okay, Unity Screen Recorder is only supported in Editor. Still finding an alternative.

**Comment by kiraio-moe** [comment]
Bruh... I didn't know making a screen recorder is hard!!

Currently, here's the tools I found interesting:
- https://github.com/shinn716/Unity-FFmpeg-ScreenRecorder
- https://github.com/thanh-nguyen-kim/Android_Screen_Recorder_Plugin

**Comment by ttttttttttttttllllllllllllll** [comment]
Regarding screen recording, according to my test results.
I currently recommend recording with OBS or other software.
Because it takes longer to generate a frame at the higher resolution(>720P).

I've used the method of recording each frame and putting it into a complete video, it's too slow and the program gets stuck.
So I don't recommend using similar methods for screen recording at this time.

**Comment by kiraio-moe** [comment]
I can confirm that.
The encoding process is pretty fast for me though, but the main problem is, it didn't capture every single frame and the app performance is killing.

The screenshot utility is fine, I already implemented.

**Comment by kiraio-moe** [comment]
Closed. The screenshot utility is already implemented, but the screen recorder utility is currently no easy way put them.
